// frontend-react/src/components/Home/index.js
import React from 'react';
import Header from '../Header'
import Header_Container from '../Header_Container'
import Content from '../Content'
import Footer from '../Footer'

export default function Home() {
 return (
   <div>
       <Header/>
       <Header_Container/>
       <Content/>
       <Footer/>
   </div>
 );
}

// frontend/src/components/Home.vue
<template>
  <div class="home-wrapper">
      <Menu />
      <MenuContainer />
      <Content />
      <Footer />

  </div>
</template>

<script>
import Menu from './Menu'
import MenuContainer from './MenuContainer'
import Content from './Content'
import Footer from './Footer'
export default {
    name: 'Home',
    components: {
        Menu,
        MenuContainer,
        Content,
        Footer
    }
}
</script>

<style>

</style>
