// frontend/src/components/Footer.vue
<template>
  <div class="footer-wrapper bg-dark">
      <span>©1999-2020</span>
      <span>Rosetta Stone Ltd Todos os direitos reservados</span>
      <span>Política de Privacidade</span>
      <span>Adriel-MClove</span>
  </div>
</template>

<script>
export default {
    name: "Footer"
}
</script>

<style>
.footer-wrapper{
    color: white;
    height: 60px;
    display: flex;
    justify-content: space-around;
    align-items: center;
    font-weight: 700;
}
</style>

// frontend-react/src/components/Footer/index.js
import React from 'react';
import './footer.css'

export default function Footer() {
 return (
    <div class="footer-wrapper bg-dark">
      <span>©1999-2020</span>
      <span>Rosetta Stone Ltd Todos os direitos reservados</span>
      <span>Política de Privacidade</span>
      <span>Adriel-MClove</span>
  </div>
 );
}
